DHCPD Server
pfsensible/core pull request #140
Opened 2024-09-28 04:44 UTC by davrosza

Changes made:

1. Added new module: `pfsensible_dhcp_server.py`, to manage DHCP server settings
2. Extended core utilities to support DHCP-specific operations
3. Added unit tests for new DHCP functionality

2025-01-26 19:45 UTC, opoplawski requested changes
Thanks for the PR!  There are a number of CI fixes to make.  Also, please add a changelog fragment.

2025-01-26 19:45 UTC, opoplawski commented on plugins/module_utils/dhcp_server.py
> +class PFSenseDHCPDServerModule(PFSenseModuleBase):
Let's call it (and related options/vars)  `DHCPServer`

2025-02-28 03:22 UTC, opoplawski commented on plugins/module_utils/dhcp_server.py
> +class PFSenseDHCPDServerModule(PFSenseModuleBase):
I think that's right.  Although I think a changelog actually isn't needed for a new module as that is handled separately, so drop that for now.  Thanks!

2025-03-06 03:37 UTC, davrosza commented on plugins/module_utils/dhcp_server.py
> +class PFSenseDHCPDServerModule(PFSenseModuleBase):
Changes completed!

2025-03-11 03:30 UTC, opoplawski requested changes
It would be good to rebase and squash down your commits as well.  Thanks again.

2025-03-11 03:30 UTC, opoplawski commented on plugins/modules/pfsense_dhcp_server.py
> +version_added: "0.1.0"
This will need to be "0.7.0"

2025-03-11 03:30 UTC, opoplawski commented on plugins/module_utils/pfsense.py
> +        self.dhcpd = self.get_element('dhcpd', create_node=True)
I don't think we should always be creating a dhcpd element.  Drop this and add `create_node=True` to the module init get_element.

2025-03-13 23:29 UTC, davrosza commented
Changes incorporated, git history squashed and rebased. Let me know if there is anything else that should be changed

2025-03-15 02:32 UTC, opoplawski approved these changes
Seems reasonable for now.  Thanks!

2025-03-15 02:32 UTC, merged