feat(phpshell): run inline php-shell code
pfsensible/core pull request #88
Opened 2023-08-25 15:52 UTC by genofire

2023-08-25 16:11 UTC, genofire commented
How does i get the linter happy?
There are no usefull debug messages.

2023-08-26 21:55 UTC, opoplawski requested changes

2023-08-26 21:55 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +    - "pfSense shell: global $debug;
This is not a valid multiline YAML string.  See https://yaml-multiline.info/

2023-12-23 00:46 UTC, opoplawski commented
I'm assuming these are straightforward:
```
ERROR: Found 3 pep8 issue(s) which need to be resolved:
ERROR: plugins/modules/pfsense_phpshell.py:56:21: W291: trailing whitespace
ERROR: plugins/modules/pfsense_phpshell.py:83:1: E302: expected 2 blank lines, found 1
ERROR: plugins/modules/pfsense_phpshell.py:117:1: E303: too many blank lines (3)
```

2023-12-23 00:56 UTC, opoplawski requested changes
As mentioned in the system patch review - I think this might be better in a different collection.  Not sure this is generally of interest for most pfsense users.  Unless you have some specific common usecases?

2023-12-23 00:56 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +# Copyright: (c) 2023, Martin Müller <martin.mueller@dataport.de>
Need GPL-3 license header

2023-12-23 00:56 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +author: Martin Müller
I think you need to add a handle in ()s

2023-12-23 00:56 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +  sample: []
You say this will return a string but the sample is an array.

2023-12-23 00:56 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +    - |
You say this will return a string but the sample is a YAML array (with one string element).

2024-01-31 02:08 UTC, opoplawski commented
Actually on second thought I think I'm fine with this being in the core collection.

2024-01-31 08:18 UTC, genofire commented
Nice, still something todo here?

2024-01-31 17:04 UTC, opoplawski requested changes

2024-01-31 17:04 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +version_added: 0.6.0
This needs to get bumped to 0.6.2

2024-02-08 04:15 UTC, opoplawski commented on plugins/modules/pfsense_phpshell.py
> +            self.module.failed_json('rc is not 0 or stderr contains output (you still could overwrite with failed_when)', **self.result)
This should be `fail_json`

2024-06-19 10:06 UTC, genofire commented
Sorry for the delay, here the changes with an rebase

2025-01-31 05:28 UTC, merged